version: "3.7"

services:
  scheduler:
    build: .
    command: bash -c "python manage.py migrate && python -u manage.py runserver 0.0.0.0:8002"
    volumes:
      - .:/app/
    ports:
      - 8002:8002