# Generated by Django 3.0.3 on 2020-03-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('schedulerID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('schedulerName', models.CharField(max_length=100, unique=True)),
                ('diagnosticsid', models.CharField(max_length=100)),
                ('correlationID', models.CharField(blank=True, max_length=100)),
                ('jobtype', models.CharField(max_length=30)),
                ('job_runs', models.IntegerField(default=0)),
                ('job_success', models.IntegerField(default=0)),
            ],
        ),
    ]
