# Generated by Django 3.0.3 on 2020-03-13 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('diagnosticsid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('correlationID', models.CharField(blank=True, max_length=100)),
                ('starttime', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=30)),
                ('lookup_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('job_runs', models.IntegerField(default=0)),
                ('job_success', models.IntegerField(default=0)),
            ],
        ),
    ]
