# Generated by Django 3.0.3 on 2020-03-02 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0004_auto_20200223_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='coid',
            new_name='diagnosticsID',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='command',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='interval',
        ),
        migrations.AddField(
            model_name='tasks',
            name='job_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasks',
            name='job_success',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasks',
            name='lookup_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
