# Generated by Django 3.0.3 on 2020-03-03 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0007_auto_20200303_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='diagnosticsid',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
    ]
