# Generated by Django 3.0.3 on 2020-03-04 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0010_tasks_correlationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='correlationID',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='diagnosticsid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
